### ISSUE TITLE
ValueError: malformed string

### ISSUE THREAD

**Issue by mortaca** [hfaran/raspberry-cereal#15]
I'm using the same GPIO ports 23, 24 and 25 of raspberry_cereal.cfg, the chip with 3.3v Vcc and GND to pin CE.
I still have the same error message:

> [WAIT] Setting up...
> Traceback (most recent call last):
>   File "/usr/local/bin/raspberry-cereal", line 9, in <module>
>     load_entry_point('raspberry-cereal==1.0.1', 'console_scripts', 'raspberry-cereal')()
>   File "build/bdist.linux-armv7l/egg/raspberry_cereal/__init__.py", line 37, in main
>   File "build/bdist.linux-armv7l/egg/raspberry_cereal/validate_cfg.py", line 28, in main
>   File "/usr/lib/python2.7/ast.py", line 80, in literal_eval
>     return _convert(node_or_string)
>   File "/usr/lib/python2.7/ast.py", line 79, in _convert
>     raise ValueError('malformed string')
> ValueError: malformed string

The project could not bring attached a small 74hc165n connection scheme?

**Comment by mortaca** [comment]
My scheme:

http://i.imgur.com/PLjahx0.png
